"""add user totp_secret

Revision ID: c24d7c6e21bb
Revises: f5f25022c8be
Create Date: 2026-06-30 15:16:48.200811

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c24d7c6e21bb'
down_revision: str | None = 'f5f25022c8be'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('totp_secret', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'totp_secret')
    # ### end Alembic commands ###
