"""add adverse_event description

Revision ID: d97ad5c881ba
Revises: c24d7c6e21bb
Create Date: 2026-06-30 15:42:35.542788

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd97ad5c881ba'
down_revision: str | None = 'c24d7c6e21bb'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('adverse_event', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('adverse_event', 'description')
    # ### end Alembic commands ###
