"""initial schema

Revision ID: f5f25022c8be
Revises: 
Create Date: 2026-06-30 15:08:23.320630

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f5f25022c8be'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('biz_no', sa.String(length=64), nullable=True),
    sa.Column('plan', sa.Enum('free', 'starter', 'growth', 'enterprise', name='plan_tier'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('owner', 'member', 'oem_manager', 'admin', name='user_role'), nullable=False),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_user_email')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
    op.create_table('workspace',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('brand_name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_log',
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('target', sa.String(length=255), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compliance_task',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('facility_renewal', 'product_listing', 'content_update', 'annual_update', 'sae_report', name='compliance_task_type'), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('assignee_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('scheduled', 'due_soon', 'overdue', 'done', name='compliance_task_status'), nullable=False),
    sa.Column('source_ref', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assignee_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_task_due_date'), 'compliance_task', ['due_date'], unique=False)
    op.create_table('document',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('owner_ref', sa.String(length=128), nullable=False),
    sa.Column('type', sa.Enum('dossier', 'label', 'spl', 'summary', 'other', name='document_type'), nullable=False),
    sa.Column('file_url', sa.String(length=1024), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_owner_ref'), 'document', ['owner_ref'], unique=False)
    op.create_table('facility',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=False),
    sa.Column('address_en', sa.String(length=512), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('fei', sa.String(length=32), nullable=True),
    sa.Column('status', sa.Enum('draft', 'submitting', 'registered', 'renewal_due', 'expired', name='facility_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facility_fei'), 'facility', ['fei'], unique=False)
    op.create_table('product',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.Column('label_url', sa.String(length=1024), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('responsible_person',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('us_contact', sa.String(length=512), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('us_agent',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=512), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('type', sa.Enum('partner', 'direct', name='us_agent_type'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('adverse_event',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('severity', sa.Enum('non_serious', 'serious', name='adverse_event_severity'), nullable=False),
    sa.Column('report_status', sa.Enum('received', 'assessing', 'reportable', 'submitted', 'closed', name='adverse_event_status'), nullable=False),
    sa.Column('reported_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingredient',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('raw_name', sa.String(length=255), nullable=False),
    sa.Column('inci_name', sa.String(length=255), nullable=True),
    sa.Column('confidence', sa.Enum('high', 'medium', 'low', name='inci_confidence'), nullable=True),
    sa.Column('flag', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_facility',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('facility_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facility.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', 'facility_id')
    )
    op.create_table('submission',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('facility_id', sa.UUID(), nullable=True),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.Enum('facility', 'product', name='submission_type'), nullable=False),
    sa.Column('spl_xml', sa.Text(), nullable=True),
    sa.Column('esg_id', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('generated', 'submitted', 'ack1', 'ack2', 'completed', 'failed', name='submission_status'), nullable=False),
    sa.Column('acked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facility.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submission_esg_id'), 'submission', ['esg_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_submission_esg_id'), table_name='submission')
    op.drop_table('submission')
    op.drop_table('product_facility')
    op.drop_table('ingredient')
    op.drop_table('adverse_event')
    op.drop_table('us_agent')
    op.drop_table('responsible_person')
    op.drop_table('product')
    op.drop_index(op.f('ix_facility_fei'), table_name='facility')
    op.drop_table('facility')
    op.drop_index(op.f('ix_document_owner_ref'), table_name='document')
    op.drop_table('document')
    op.drop_index(op.f('ix_compliance_task_due_date'), table_name='compliance_task')
    op.drop_table('compliance_task')
    op.drop_table('audit_log')
    op.drop_table('workspace')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('organization')
    # ### end Alembic commands ###
